# Generated by Django 4.2.7 on 2023-12-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="set_num",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
