# Generated by Django 4.2.7 on 2023-12-09 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0002_set_set_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="set_num",
        ),
    ]
