# Generated by Django 4.2.7 on 2023-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.IntegerField(blank=True),
        ),
    ]
