# Generated by Django 4.2.7 on 2023-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0003_remove_set_set_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="set_num",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
