# Generated by Django 4.2.7 on 2023-12-03 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0003_alter_user_age_alter_user_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
    ]
