# Generated by Django 4.2.7 on 2023-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0004_set_set_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
