# Generated by Django 4.2.7 on 2023-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0004_remove_user_age_remove_user_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
