# Generated by Django 4.2.7 on 2023-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0005_alter_set_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="exercise_num",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
