# Generated by Django 4.2.7 on 2023-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0005_user_age_user_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="sets",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="ProgressiveFitness.set"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="workouts",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="ProgressiveFitness.workout"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="exercies",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="ProgressiveFitness.exercise"
            ),
        ),
    ]
