# Generated by Django 4.2.7 on 2023-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0006_alter_exercise_sets_alter_user_workouts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="set",
            name="set_number",
        ),
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
