# Generated by Django 4.2.7 on 2023-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ProgressiveFitness",
            "0007_alter_set_set_num_alter_set_weight_alter_user_weight",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="set_num",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="set",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
