# Generated by Django 4.2.7 on 2023-12-05 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0007_remove_set_set_number_alter_set_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="exercies",
            new_name="exercises",
        ),
    ]
