# Generated by Django 4.2.7 on 2023-12-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ProgressiveFitness",
            "0008_alter_set_set_num_alter_set_weight_alter_user_weight",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="set_num",
            field=models.IntegerField(),
        ),
    ]
