# Generated by Django 4.2.7 on 2023-12-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0009_alter_set_set_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="projected_day",
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
