# Generated by Django 4.2.7 on 2023-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0010_workout_completed_date_workout_projected_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
