# Generated by Django 4.2.7 on 2023-12-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0012_split_user_splits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_split",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="User",
                to="ProgressiveFitness.split",
            ),
        ),
    ]
