# Generated by Django 4.2.7 on 2023-12-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0013_user_current_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bench",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="current_split",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="User",
                to="ProgressiveFitness.split",
            ),
        ),
    ]
