# Generated by Django 4.2.7 on 2023-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0014_user_bench_alter_user_current_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="thread_id",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
