# Generated by Django 4.2.7 on 2024-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProgressiveFitness", "0015_user_thread_id_alter_workout_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="target_reps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="target_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
